spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_shiro?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: test
    password: test
#    schema: database/import.sql
#    sql-script-encoding: utf-8

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  thymeleaf:
    cache: false
    mode: HTML